// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: keepalive/nats/nats.proto

package pbnats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Packet 用于描述一个包
type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*Packet_GOP
	//	*Packet_AP
	//	*Packet_OFF
	Msg isPacket_Msg `protobuf_oneof:"Msg"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_nats_nats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_nats_nats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_keepalive_nats_nats_proto_rawDescGZIP(), []int{0}
}

func (m *Packet) GetMsg() isPacket_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Packet) GetGOP() *Group {
	if x, ok := x.GetMsg().(*Packet_GOP); ok {
		return x.GOP
	}
	return nil
}

func (x *Packet) GetAP() *App {
	if x, ok := x.GetMsg().(*Packet_AP); ok {
		return x.AP
	}
	return nil
}

func (x *Packet) GetOFF() *ForcedOFF {
	if x, ok := x.GetMsg().(*Packet_OFF); ok {
		return x.OFF
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_GOP struct {
	// GOP 群发消息体
	GOP *Group `protobuf:"bytes,2,opt,name=GOP,proto3,oneof"`
}

type Packet_AP struct {
	// AP 群发消息
	AP *App `protobuf:"bytes,3,opt,name=AP,proto3,oneof"`
}

type Packet_OFF struct {
	// OFF 强制下线
	OFF *ForcedOFF `protobuf:"bytes,4,opt,name=OFF,proto3,oneof"`
}

func (*Packet_GOP) isPacket_Msg() {}

func (*Packet_AP) isPacket_Msg() {}

func (*Packet_OFF) isPacket_Msg() {}

// ForcedOFF 强制下线
type ForcedOFF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForcedOFF) Reset() {
	*x = ForcedOFF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_nats_nats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForcedOFF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForcedOFF) ProtoMessage() {}

func (x *ForcedOFF) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_nats_nats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForcedOFF.ProtoReflect.Descriptor instead.
func (*ForcedOFF) Descriptor() ([]byte, []int) {
	return file_keepalive_nats_nats_proto_rawDescGZIP(), []int{1}
}

// Group 群发 1对M
type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Body 数据体
	Body []byte `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty" xorm:"blob 'Body'"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_nats_nats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_nats_nats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_keepalive_nats_nats_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// App 在线广播
type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AppID 应用程序的ID
	AppID string `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty" xorm:"varchar(255) unsigned not null default '' 'AppID'"`
	// Body 下发数据体
	Body []byte `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty" xorm:"blob 'Body'"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_nats_nats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_nats_nats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_keepalive_nats_nats_proto_rawDescGZIP(), []int{3}
}

func (x *App) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *App) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_keepalive_nats_nats_proto protoreflect.FileDescriptor

var file_keepalive_nats_nats_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x6e, 0x61, 0x74, 0x73,
	0x2f, 0x6e, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x4b, 0x65, 0x65,
	0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x4e, 0x61, 0x74, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x06,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x47, 0x4f, 0x50, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e,
	0x4e, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x00, 0x52, 0x03, 0x47, 0x4f,
	0x50, 0x12, 0x25, 0x0a, 0x02, 0x41, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x4e, 0x61, 0x74, 0x73, 0x2e, 0x41,
	0x70, 0x70, 0x48, 0x00, 0x52, 0x02, 0x41, 0x50, 0x12, 0x2d, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x2e, 0x4e, 0x61, 0x74, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x64, 0x4f, 0x46, 0x46,
	0x48, 0x00, 0x52, 0x03, 0x4f, 0x46, 0x46, 0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x0b,
	0x0a, 0x09, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x64, 0x4f, 0x46, 0x46, 0x22, 0x1b, 0x0a, 0x05, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x2f, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x41, 0x70, 0x70, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x88, 0x01, 0x0a, 0x1c, 0x7a, 0x77,
	0x77, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x6e, 0x61, 0x74, 0x73, 0x42, 0x06, 0x50, 0x42, 0x4e, 0x61,
	0x74, 0x73, 0x50, 0x01, 0x5a, 0x33, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x2f, 0x6b, 0x65, 0x65,
	0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x6e, 0x61, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x6e, 0x61,
	0x74, 0x73, 0x3b, 0x70, 0x62, 0x6e, 0x61, 0x74, 0x73, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x06, 0x50,
	0x42, 0x4e, 0x61, 0x74, 0x73, 0xaa, 0x02, 0x1c, 0x5a, 0x77, 0x77, 0x78, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e,
	0x4e, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keepalive_nats_nats_proto_rawDescOnce sync.Once
	file_keepalive_nats_nats_proto_rawDescData = file_keepalive_nats_nats_proto_rawDesc
)

func file_keepalive_nats_nats_proto_rawDescGZIP() []byte {
	file_keepalive_nats_nats_proto_rawDescOnce.Do(func() {
		file_keepalive_nats_nats_proto_rawDescData = protoimpl.X.CompressGZIP(file_keepalive_nats_nats_proto_rawDescData)
	})
	return file_keepalive_nats_nats_proto_rawDescData
}

var file_keepalive_nats_nats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_keepalive_nats_nats_proto_goTypes = []interface{}{
	(*Packet)(nil),    // 0: Keepalive.Nats.Packet
	(*ForcedOFF)(nil), // 1: Keepalive.Nats.ForcedOFF
	(*Group)(nil),     // 2: Keepalive.Nats.Group
	(*App)(nil),       // 3: Keepalive.Nats.App
}
var file_keepalive_nats_nats_proto_depIdxs = []int32{
	2, // 0: Keepalive.Nats.Packet.GOP:type_name -> Keepalive.Nats.Group
	3, // 1: Keepalive.Nats.Packet.AP:type_name -> Keepalive.Nats.App
	1, // 2: Keepalive.Nats.Packet.OFF:type_name -> Keepalive.Nats.ForcedOFF
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_keepalive_nats_nats_proto_init() }
func file_keepalive_nats_nats_proto_init() {
	if File_keepalive_nats_nats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keepalive_nats_nats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keepalive_nats_nats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForcedOFF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keepalive_nats_nats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keepalive_nats_nats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keepalive_nats_nats_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_GOP)(nil),
		(*Packet_AP)(nil),
		(*Packet_OFF)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keepalive_nats_nats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keepalive_nats_nats_proto_goTypes,
		DependencyIndexes: file_keepalive_nats_nats_proto_depIdxs,
		MessageInfos:      file_keepalive_nats_nats_proto_msgTypes,
	}.Build()
	File_keepalive_nats_nats_proto = out.File
	file_keepalive_nats_nats_proto_rawDesc = nil
	file_keepalive_nats_nats_proto_goTypes = nil
	file_keepalive_nats_nats_proto_depIdxs = nil
}
