// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: common/app.proto

package pbm_app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App int32

const (
	// AP_UNKNOWN 未知的应用类型
	App_AP_UNKNOWN App = 0
	// AP_GAME_MASTER  GM后台
	App_AP_GAME_MASTER App = 1
	// AP_GAME_FRONTEND 游戏前端
	App_AP_GAME_FRONTEND App = 2
	// AP_GAME_SDK SDK应用
	App_AP_GAME_SDK App = 3
)

// Enum value maps for App.
var (
	App_name = map[int32]string{
		0: "AP_UNKNOWN",
		1: "AP_GAME_MASTER",
		2: "AP_GAME_FRONTEND",
		3: "AP_GAME_SDK",
	}
	App_value = map[string]int32{
		"AP_UNKNOWN":       0,
		"AP_GAME_MASTER":   1,
		"AP_GAME_FRONTEND": 2,
		"AP_GAME_SDK":      3,
	}
)

func (x App) Enum() *App {
	p := new(App)
	*p = x
	return p
}

func (x App) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App) Descriptor() protoreflect.EnumDescriptor {
	return file_common_app_proto_enumTypes[0].Descriptor()
}

func (App) Type() protoreflect.EnumType {
	return &file_common_app_proto_enumTypes[0]
}

func (x App) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App.Descriptor instead.
func (App) EnumDescriptor() ([]byte, []int) {
	return file_common_app_proto_rawDescGZIP(), []int{0}
}

var File_common_app_proto protoreflect.FileDescriptor

var file_common_app_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x50, 0x0a, 0x03, 0x41, 0x70,
	0x70, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x50, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4d, 0x41, 0x53,
	0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x50, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x46, 0x52, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41,
	0x50, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x44, 0x4b, 0x10, 0x03, 0x42, 0x49, 0x5a, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62,
	0x6d, 0x5f, 0x61, 0x70, 0x70, 0x3b, 0x70, 0x62, 0x6d, 0x5f, 0x61, 0x70, 0x70, 0xf8, 0x01, 0x01,
	0xaa, 0x02, 0x14, 0x5a, 0x77, 0x77, 0x78, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_app_proto_rawDescOnce sync.Once
	file_common_app_proto_rawDescData = file_common_app_proto_rawDesc
)

func file_common_app_proto_rawDescGZIP() []byte {
	file_common_app_proto_rawDescOnce.Do(func() {
		file_common_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_app_proto_rawDescData)
	})
	return file_common_app_proto_rawDescData
}

var file_common_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_app_proto_goTypes = []interface{}{
	(App)(0), // 0: Common.App
}
var file_common_app_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_app_proto_init() }
func file_common_app_proto_init() {
	if File_common_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_app_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_app_proto_goTypes,
		DependencyIndexes: file_common_app_proto_depIdxs,
		EnumInfos:         file_common_app_proto_enumTypes,
	}.Build()
	File_common_app_proto = out.File
	file_common_app_proto_rawDesc = nil
	file_common_app_proto_goTypes = nil
	file_common_app_proto_depIdxs = nil
}
