// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: keepalive/s2c/S2C.proto

package pbs2c

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command 用于描述客户端到服务端的行为
type Command int32

const (
	// C_INVALID 无效
	Command_C_INVALID Command = 0
	// C_PONG 对于Ping的响应
	Command_C_PONG Command = 1
	// C_AUTH 对于Auth的响应
	Command_C_AUTH Command = 2
	// C_FORCED_OFF 强制下线
	Command_C_FORCED_OFF Command = 3
	// C_BUSSINESS 业务消息
	Command_C_BUSSINESS Command = 4
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "C_INVALID",
		1: "C_PONG",
		2: "C_AUTH",
		3: "C_FORCED_OFF",
		4: "C_BUSSINESS",
	}
	Command_value = map[string]int32{
		"C_INVALID":    0,
		"C_PONG":       1,
		"C_AUTH":       2,
		"C_FORCED_OFF": 3,
		"C_BUSSINESS":  4,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_keepalive_s2c_S2C_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_keepalive_s2c_S2C_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_keepalive_s2c_S2C_proto_rawDescGZIP(), []int{0}
}

// S2CBussiness 不同应用的业务消息
type S2CBussiness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Body 用于表示业务数据体
	Body []byte `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty" xorm:"blob 'Body'"`
}

func (x *S2CBussiness) Reset() {
	*x = S2CBussiness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_s2c_S2C_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CBussiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CBussiness) ProtoMessage() {}

func (x *S2CBussiness) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_s2c_S2C_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CBussiness.ProtoReflect.Descriptor instead.
func (*S2CBussiness) Descriptor() ([]byte, []int) {
	return file_keepalive_s2c_S2C_proto_rawDescGZIP(), []int{0}
}

func (x *S2CBussiness) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// S2CForcedOFF 强制下线的通知
type S2CForcedOFF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CForcedOFF) Reset() {
	*x = S2CForcedOFF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_s2c_S2C_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CForcedOFF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CForcedOFF) ProtoMessage() {}

func (x *S2CForcedOFF) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_s2c_S2C_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CForcedOFF.ProtoReflect.Descriptor instead.
func (*S2CForcedOFF) Descriptor() ([]byte, []int) {
	return file_keepalive_s2c_S2C_proto_rawDescGZIP(), []int{1}
}

// S2CPong 对于Pong消息的响应
type S2CPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timstamp 时间戳
	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty" xorm:"bigint not null default 0 'Timestamp'"`
}

func (x *S2CPong) Reset() {
	*x = S2CPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_s2c_S2C_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPong) ProtoMessage() {}

func (x *S2CPong) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_s2c_S2C_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPong.ProtoReflect.Descriptor instead.
func (*S2CPong) Descriptor() ([]byte, []int) {
	return file_keepalive_s2c_S2C_proto_rawDescGZIP(), []int{2}
}

func (x *S2CPong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// S2CAuth 对于Auth消息的响应
type S2CAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CAuth) Reset() {
	*x = S2CAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_s2c_S2C_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuth) ProtoMessage() {}

func (x *S2CAuth) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_s2c_S2C_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuth.ProtoReflect.Descriptor instead.
func (*S2CAuth) Descriptor() ([]byte, []int) {
	return file_keepalive_s2c_S2C_proto_rawDescGZIP(), []int{3}
}

var File_keepalive_s2c_S2C_proto protoreflect.FileDescriptor

var file_keepalive_s2c_S2C_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x73, 0x32, 0x63, 0x2f,
	0x53, 0x32, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x61,
	0x6c, 0x69, 0x76, 0x65, 0x2e, 0x53, 0x32, 0x43, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x42,
	0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x0e, 0x0a, 0x0c,
	0x53, 0x32, 0x43, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x64, 0x4f, 0x46, 0x46, 0x22, 0x27, 0x0a, 0x07,
	0x53, 0x32, 0x43, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x41, 0x75, 0x74, 0x68,
	0x2a, 0x53, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x5f,
	0x50, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x5f, 0x41, 0x55, 0x54, 0x48,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x44, 0x5f, 0x4f,
	0x46, 0x46, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x5f, 0x42, 0x55, 0x53, 0x53, 0x49, 0x4e,
	0x45, 0x53, 0x53, 0x10, 0x04, 0x42, 0x81, 0x01, 0x0a, 0x1b, 0x7a, 0x77, 0x77, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x2e, 0x53, 0x32, 0x43, 0x42, 0x05, 0x50, 0x42, 0x53, 0x32, 0x43, 0x50, 0x01, 0x5a, 0x30,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x2f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65,
	0x2f, 0x73, 0x32, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x32, 0x63, 0x3b, 0x70, 0x62, 0x73, 0x32, 0x63,
	0xf8, 0x01, 0x01, 0xa2, 0x02, 0x05, 0x50, 0x42, 0x53, 0x32, 0x43, 0xaa, 0x02, 0x1b, 0x5a, 0x77,
	0x77, 0x78, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4b, 0x65, 0x65, 0x70,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x53, 0x32, 0x43, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_keepalive_s2c_S2C_proto_rawDescOnce sync.Once
	file_keepalive_s2c_S2C_proto_rawDescData = file_keepalive_s2c_S2C_proto_rawDesc
)

func file_keepalive_s2c_S2C_proto_rawDescGZIP() []byte {
	file_keepalive_s2c_S2C_proto_rawDescOnce.Do(func() {
		file_keepalive_s2c_S2C_proto_rawDescData = protoimpl.X.CompressGZIP(file_keepalive_s2c_S2C_proto_rawDescData)
	})
	return file_keepalive_s2c_S2C_proto_rawDescData
}

var file_keepalive_s2c_S2C_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keepalive_s2c_S2C_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_keepalive_s2c_S2C_proto_goTypes = []interface{}{
	(Command)(0),         // 0: Keepalive.S2C.Command
	(*S2CBussiness)(nil), // 1: Keepalive.S2C.S2CBussiness
	(*S2CForcedOFF)(nil), // 2: Keepalive.S2C.S2CForcedOFF
	(*S2CPong)(nil),      // 3: Keepalive.S2C.S2CPong
	(*S2CAuth)(nil),      // 4: Keepalive.S2C.S2CAuth
}
var file_keepalive_s2c_S2C_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keepalive_s2c_S2C_proto_init() }
func file_keepalive_s2c_S2C_proto_init() {
	if File_keepalive_s2c_S2C_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keepalive_s2c_S2C_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CBussiness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keepalive_s2c_S2C_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CForcedOFF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keepalive_s2c_S2C_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keepalive_s2c_S2C_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keepalive_s2c_S2C_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keepalive_s2c_S2C_proto_goTypes,
		DependencyIndexes: file_keepalive_s2c_S2C_proto_depIdxs,
		EnumInfos:         file_keepalive_s2c_S2C_proto_enumTypes,
		MessageInfos:      file_keepalive_s2c_S2C_proto_msgTypes,
	}.Build()
	File_keepalive_s2c_S2C_proto = out.File
	file_keepalive_s2c_S2C_proto_rawDesc = nil
	file_keepalive_s2c_S2C_proto_goTypes = nil
	file_keepalive_s2c_S2C_proto_depIdxs = nil
}
