// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: common/pattern.proto

package pbm_pattern

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pattern 代表强制下线的策略
type Pattern int32

const (
	// P_UNKNOWN 默认值,无效
	Pattern_P_UNKNOWN Pattern = 0
	// MUTEX 各种操作系统互斥
	Pattern_P_MUTEX Pattern = 1
	// PARALLEL 各种操作系统并行
	Pattern_P_PARALLEL Pattern = 2
)

// Enum value maps for Pattern.
var (
	Pattern_name = map[int32]string{
		0: "P_UNKNOWN",
		1: "P_MUTEX",
		2: "P_PARALLEL",
	}
	Pattern_value = map[string]int32{
		"P_UNKNOWN":  0,
		"P_MUTEX":    1,
		"P_PARALLEL": 2,
	}
)

func (x Pattern) Enum() *Pattern {
	p := new(Pattern)
	*p = x
	return p
}

func (x Pattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pattern) Descriptor() protoreflect.EnumDescriptor {
	return file_common_pattern_proto_enumTypes[0].Descriptor()
}

func (Pattern) Type() protoreflect.EnumType {
	return &file_common_pattern_proto_enumTypes[0]
}

func (x Pattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pattern.Descriptor instead.
func (Pattern) EnumDescriptor() ([]byte, []int) {
	return file_common_pattern_proto_rawDescGZIP(), []int{0}
}

var File_common_pattern_proto protoreflect.FileDescriptor

var file_common_pattern_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x35,
	0x0a, 0x07, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x5f, 0x4d, 0x55,
	0x54, 0x45, 0x58, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4c,
	0x4c, 0x45, 0x4c, 0x10, 0x02, 0x42, 0x59, 0x5a, 0x35, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x6d, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x3b, 0x70, 0x62, 0x6d, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0xf8, 0x01,
	0x01, 0xaa, 0x02, 0x1c, 0x5a, 0x77, 0x77, 0x78, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_pattern_proto_rawDescOnce sync.Once
	file_common_pattern_proto_rawDescData = file_common_pattern_proto_rawDesc
)

func file_common_pattern_proto_rawDescGZIP() []byte {
	file_common_pattern_proto_rawDescOnce.Do(func() {
		file_common_pattern_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_pattern_proto_rawDescData)
	})
	return file_common_pattern_proto_rawDescData
}

var file_common_pattern_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_pattern_proto_goTypes = []interface{}{
	(Pattern)(0), // 0: Common.Pattern
}
var file_common_pattern_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_pattern_proto_init() }
func file_common_pattern_proto_init() {
	if File_common_pattern_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_pattern_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_pattern_proto_goTypes,
		DependencyIndexes: file_common_pattern_proto_depIdxs,
		EnumInfos:         file_common_pattern_proto_enumTypes,
	}.Build()
	File_common_pattern_proto = out.File
	file_common_pattern_proto_rawDesc = nil
	file_common_pattern_proto_goTypes = nil
	file_common_pattern_proto_depIdxs = nil
}
