// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: common/token.proto

package pbm_token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	pbm_channel "unary/protocol/generate/gopb/common/pbm_channel"
	pbm_os "unary/protocol/generate/gopb/common/pbm_os"
	pbm_pattern "unary/protocol/generate/gopb/common/pbm_pattern"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//  Token 用于描述一个令牌信息结构
type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UID 应用程序ID
	UID uint64 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty" xorm:"bigint unsigned not null default 0 'UID'"`
	// Timestamp 当前的时间戳
	Timestamp int64 `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty" xorm:"bigint not null default 0 'Timestamp'"`
	// AppID 应用程序ID
	AppID string `protobuf:"bytes,3,opt,name=AppID,proto3" json:"AppID,omitempty" xorm:"varchar(255) unsigned not null default '' 'AppID'"`
	// System 操作系统
	System pbm_os.OS `protobuf:"varint,4,opt,name=System,proto3,enum=Common.OS" json:"System,omitempty" xorm:"int unsigned not null default 0 'System'"`
	// Channel 渠道
	Channel pbm_channel.Channel `protobuf:"varint,5,opt,name=Channel,proto3,enum=Common.Channel" json:"Channel,omitempty" xorm:"int unsigned not null default 0 'Channel'"`
	// Pattern 模式,即多系统在线,还是单一系统在线
	Pattern pbm_pattern.Pattern `protobuf:"varint,6,opt,name=Pattern,proto3,enum=Common.Pattern" json:"Pattern,omitempty" xorm:"int unsigned not null default 0 'Pattern'"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_common_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_common_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Token) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Token) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *Token) GetSystem() pbm_os.OS {
	if x != nil {
		return x.System
	}
	return pbm_os.OS_OS_UNKNOWN
}

func (x *Token) GetChannel() pbm_channel.Channel {
	if x != nil {
		return x.Channel
	}
	return pbm_channel.Channel_C_UNKNWON
}

func (x *Token) GetPattern() pbm_pattern.Pattern {
	if x != nil {
		return x.Pattern
	}
	return pbm_pattern.Pattern_P_UNKNOWN
}

var File_common_token_proto protoreflect.FileDescriptor

var file_common_token_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x0f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x06, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4f, 0x53, 0x52, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x29, 0x0a,
	0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x29, 0x0a, 0x07, 0x50, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x52, 0x07, 0x50, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x42, 0x50, 0x5a, 0x31, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3b, 0x70,
	0x62, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0xaa, 0x02, 0x1a, 0x5a, 0x77, 0x77, 0x78, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_token_proto_rawDescOnce sync.Once
	file_common_token_proto_rawDescData = file_common_token_proto_rawDesc
)

func file_common_token_proto_rawDescGZIP() []byte {
	file_common_token_proto_rawDescOnce.Do(func() {
		file_common_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_token_proto_rawDescData)
	})
	return file_common_token_proto_rawDescData
}

var file_common_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_token_proto_goTypes = []interface{}{
	(*Token)(nil),            // 0: Common.Token
	(pbm_os.OS)(0),           // 1: Common.OS
	(pbm_channel.Channel)(0), // 2: Common.Channel
	(pbm_pattern.Pattern)(0), // 3: Common.Pattern
}
var file_common_token_proto_depIdxs = []int32{
	1, // 0: Common.Token.System:type_name -> Common.OS
	2, // 1: Common.Token.Channel:type_name -> Common.Channel
	3, // 2: Common.Token.Pattern:type_name -> Common.Pattern
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_token_proto_init() }
func file_common_token_proto_init() {
	if File_common_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_token_proto_goTypes,
		DependencyIndexes: file_common_token_proto_depIdxs,
		MessageInfos:      file_common_token_proto_msgTypes,
	}.Build()
	File_common_token_proto = out.File
	file_common_token_proto_rawDesc = nil
	file_common_token_proto_goTypes = nil
	file_common_token_proto_depIdxs = nil
}
