// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: common/os.proto

package pbm_os

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OS 代表的是操作系统
type OS int32

const (
	// OS_UNKNOWN 操作系统未知
	OS_OS_UNKNOWN OS = 0
	// OS_ANDROID 操作系统为android
	OS_OS_ANDROID OS = 1
	// OS_IOS 操作系统为IOS
	OS_OS_IOS OS = 2
	// OS_WINDOWS 操作系统为windows
	OS_OS_WINDOWS OS = 3
	// OS_LINUX 操作系统为linux
	OS_OS_LINUX OS = 4
	// OS_IPAD 操作系统为IPAD
	OS_OS_IPAD OS = 5
)

// Enum value maps for OS.
var (
	OS_name = map[int32]string{
		0: "OS_UNKNOWN",
		1: "OS_ANDROID",
		2: "OS_IOS",
		3: "OS_WINDOWS",
		4: "OS_LINUX",
		5: "OS_IPAD",
	}
	OS_value = map[string]int32{
		"OS_UNKNOWN": 0,
		"OS_ANDROID": 1,
		"OS_IOS":     2,
		"OS_WINDOWS": 3,
		"OS_LINUX":   4,
		"OS_IPAD":    5,
	}
)

func (x OS) Enum() *OS {
	p := new(OS)
	*p = x
	return p
}

func (x OS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OS) Descriptor() protoreflect.EnumDescriptor {
	return file_common_os_proto_enumTypes[0].Descriptor()
}

func (OS) Type() protoreflect.EnumType {
	return &file_common_os_proto_enumTypes[0]
}

func (x OS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OS.Descriptor instead.
func (OS) EnumDescriptor() ([]byte, []int) {
	return file_common_os_proto_rawDescGZIP(), []int{0}
}

var File_common_os_proto protoreflect.FileDescriptor

var file_common_os_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x5b, 0x0a, 0x02, 0x4f, 0x53, 0x12,
	0x0e, 0x0a, 0x0a, 0x4f, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x4f, 0x53, 0x5f, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x4f, 0x53, 0x5f, 0x49, 0x4f, 0x53, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4f,
	0x53, 0x5f, 0x57, 0x49, 0x4e, 0x44, 0x4f, 0x57, 0x53, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4f,
	0x53, 0x5f, 0x4c, 0x49, 0x4e, 0x55, 0x58, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x53, 0x5f,
	0x49, 0x50, 0x41, 0x44, 0x10, 0x05, 0x42, 0x47, 0x5a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x70, 0x62,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x6d, 0x5f, 0x6f, 0x73, 0x3b, 0x70,
	0x62, 0x6d, 0x5f, 0x6f, 0x73, 0xf8, 0x01, 0x01, 0xaa, 0x02, 0x14, 0x5a, 0x77, 0x77, 0x78, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_os_proto_rawDescOnce sync.Once
	file_common_os_proto_rawDescData = file_common_os_proto_rawDesc
)

func file_common_os_proto_rawDescGZIP() []byte {
	file_common_os_proto_rawDescOnce.Do(func() {
		file_common_os_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_os_proto_rawDescData)
	})
	return file_common_os_proto_rawDescData
}

var file_common_os_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_os_proto_goTypes = []interface{}{
	(OS)(0), // 0: Common.OS
}
var file_common_os_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_os_proto_init() }
func file_common_os_proto_init() {
	if File_common_os_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_os_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_os_proto_goTypes,
		DependencyIndexes: file_common_os_proto_depIdxs,
		EnumInfos:         file_common_os_proto_enumTypes,
	}.Build()
	File_common_os_proto = out.File
	file_common_os_proto_rawDesc = nil
	file_common_os_proto_goTypes = nil
	file_common_os_proto_depIdxs = nil
}
